// <auto-generated />
using MatanzaBikes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatanzaBikes.Migrations
{
    [DbContext(typeof(MatanzaBikesContext))]
    [Migration("20231107015100_MatanzaBikes")]
    partial class MatanzaBikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatanzaBikes.Model.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ducati"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Harley Davidson"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Honda"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Yamaha"
                        });
                });

            modelBuilder.Entity("MatanzaBikes.Model.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Bateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frenos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("Rodado")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Suspension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "Mongolia",
                            Motor = "4 tiempos",
                            Peso = 197,
                            Precio = 238m,
                            Rodado = 207.0,
                            Stock = 572,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 4,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Greece",
                            Motor = "4 tiempos",
                            Peso = 112,
                            Precio = 244m,
                            Rodado = 271.0,
                            Stock = 608,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 5,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "Equatorial Guinea",
                            Motor = "4 tiempos",
                            Peso = 360,
                            Precio = 269m,
                            Rodado = 367.0,
                            Stock = 341,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 6,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Bermuda",
                            Motor = "4 tiempos",
                            Peso = 251,
                            Precio = 236m,
                            Rodado = 215.0,
                            Stock = 843,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 7,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Belarus",
                            Motor = "4 tiempos",
                            Peso = 388,
                            Precio = 267m,
                            Rodado = 61.0,
                            Stock = 701,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 8,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Brazil",
                            Motor = "4 tiempos",
                            Peso = 338,
                            Precio = 126m,
                            Rodado = 105.0,
                            Stock = 33,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 9,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "Germany",
                            Motor = "4 tiempos",
                            Peso = 273,
                            Precio = 86m,
                            Rodado = 34.0,
                            Stock = 726,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 10,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "Virgin Islands (U.S.)",
                            Motor = "4 tiempos",
                            Peso = 305,
                            Precio = 19m,
                            Rodado = 143.0,
                            Stock = 386,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 11,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Côte d'Ivoire",
                            Motor = "4 tiempos",
                            Peso = 361,
                            Precio = 291m,
                            Rodado = 5.0,
                            Stock = 235,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 12,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Costa Rica",
                            Motor = "4 tiempos",
                            Peso = 294,
                            Precio = 183m,
                            Rodado = 53.0,
                            Stock = 676,
                            Suspension = "Hidraulica"
                        });
                });

            modelBuilder.Entity("MatanzaBikes.Model.Moto", b =>
                {
                    b.HasOne("MatanzaBikes.Model.Marca", null)
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
