// <auto-generated />
using MatanzaBikes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatanzaBikes.Migrations
{
    [DbContext(typeof(MatanzaBikesContext))]
    [Migration("20231111012808_MatanzaBikes")]
    partial class MatanzaBikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatanzaBikes.Model.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ducati"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Harley Davidson"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Honda"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Yamaha"
                        });
                });

            modelBuilder.Entity("MatanzaBikes.Model.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Bateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frenos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("Rodado")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Suspension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Motos");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "New Zealand",
                            Motor = "4 tiempos",
                            Peso = 216,
                            Precio = 226m,
                            Rodado = 239.0,
                            Stock = 262,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 4,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Egypt, Arab Rep.",
                            Motor = "4 tiempos",
                            Peso = 363,
                            Precio = 241m,
                            Rodado = 311.0,
                            Stock = 532,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 5,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Suriname",
                            Motor = "4 tiempos",
                            Peso = 376,
                            Precio = 259m,
                            Rodado = 218.0,
                            Stock = 820,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 6,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Yemen, Rep.",
                            Motor = "4 tiempos",
                            Peso = 368,
                            Precio = 183m,
                            Rodado = 22.0,
                            Stock = 786,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 7,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Zimbabwe",
                            Motor = "4 tiempos",
                            Peso = 195,
                            Precio = 45m,
                            Rodado = 148.0,
                            Stock = 636,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 8,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Azerbaijan",
                            Motor = "4 tiempos",
                            Peso = 385,
                            Precio = 140m,
                            Rodado = 10.0,
                            Stock = 319,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 9,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "India",
                            Motor = "4 tiempos",
                            Peso = 275,
                            Precio = 272m,
                            Rodado = 385.0,
                            Stock = 190,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 10,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 2,
                            Modelo = "Eritrea",
                            Motor = "4 tiempos",
                            Peso = 241,
                            Precio = 187m,
                            Rodado = 25.0,
                            Stock = 645,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 11,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 1,
                            Modelo = "Korea, Dem. Rep.",
                            Motor = "4 tiempos",
                            Peso = 246,
                            Precio = 177m,
                            Rodado = 290.0,
                            Stock = 204,
                            Suspension = "Hidraulica"
                        },
                        new
                        {
                            Id = 12,
                            Año = 2023,
                            Bateria = "12",
                            Cilindrada = "650",
                            Color = "Verde",
                            Frenos = "Disco",
                            MarcaId = 3,
                            Modelo = "Kiribati",
                            Motor = "4 tiempos",
                            Peso = 272,
                            Precio = 256m,
                            Rodado = 184.0,
                            Stock = 816,
                            Suspension = "Hidraulica"
                        });
                });

            modelBuilder.Entity("MatanzaBikes.Model.Moto", b =>
                {
                    b.HasOne("MatanzaBikes.Model.Marca", null)
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
